### ISSUE TITLE
Win64 & anaconda: Issue on import after install via conda

### ISSUE THREAD

**Issue by fmaume** [konstantint/matplotlib-venn#43]
I tried to install the package on Win using anaconda conda install:
https://anaconda.org/conda-forge/matplotlib-venn

But when I'm trying to run `from matplotlib_venn import venn2, venn2_circles` I'm getting the error `TypeError: 'NoneType' object is not iterable`

Here is the traceback:
```
Traceback (most recent call last):

  File "<ipython-input-1-3dd89cb2c4d4>", line 1, in <module>
    from matplotlib_venn import venn2, venn2_circles

  File "C:\Users\Adele\Anaconda3\lib\site-packages\matplotlib_venn\__init__.py", line 55, in <module>
    from matplotlib_venn._venn2 import venn2, venn2_circles

  File "C:\Users\Adele\Anaconda3\lib\site-packages\matplotlib_venn\_venn2.py", line 22, in <module>
    from matplotlib.pyplot import gca

  File "C:\Users\Adele\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 32, in <module>
    import matplotlib.colorbar

  File "C:\Users\Adele\Anaconda3\lib\site-packages\matplotlib\colorbar.py", line 32, in <module>
    import matplotlib.contour as contour

  File "C:\Users\Adele\Anaconda3\lib\site-packages\matplotlib\contour.py", line 18, in <module>
    import matplotlib.font_manager as font_manager

  File "C:\Users\Adele\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 1363, in <module>
    _rebuild()

  File "C:\Users\Adele\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 1344, in _rebuild
    fontManager = FontManager()

  File "C:\Users\Adele\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 978, in __init__
    ttffiles = findSystemFonts(paths) + findSystemFonts()

  File "C:\Users\Adele\Anaconda3\lib\site-packages\matplotlib\font_manager.py", line 264, in findSystemFonts
    fontfiles.update(win32InstalledFonts(fontext=fontext))
```

**Comment by konstantint** [comment]
This looks like an instance of [this matplotlib issue](https://github.com/matplotlib/matplotlib/issues/12173), which should be fixed in the latest versions.
